name: Deploy release to dev

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout release
        uses: actions/checkout@v7

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftp
          port: 21
          timeout: 60000

          local-dir: ./
          server-dir: ./hhs/portfolio-wpfw/

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
